name: Build & Publish to npm

on:
  push:
    tags:
      - 'v*' # np. v0.1.0, v1.0.0

jobs:
  publish:
    name: Publish ngx-lite-tools
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npx nx build ngx-lite-tools

      - name: Publish to npm
        run: npm publish --access public
        working-directory: dist/ngx-lite-tools
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
